import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

import Navbar from "./components/Navbar";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nextflix Web Application",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative w-screen h-screen">
          <Image
            src="/Main Show BG.png"
            alt="hero"
            fill
            className="object-cover"
          />
            <div className="absolute top-0 left-0 w-full z-10 bg-gradient-to-b from-black/80 to-transparent">
              <Navbar/>
            </div>
            <div className="relative z-0 px-12">
            {children}
            </div>
        
        </div>
        
      </body>
    </html>
  );
}
